stages:
  - build
  - deploy

#########
# Build #
#########

buildnios:
  stage: build
  variables:
  script:
  - echo "(Nios) Building git branch "%CI_COMMIT_REF_NAME%" at commit "%CI_COMMIT_SHA%" short %CI_COMMIT_SHORT_SHA%"
  - echo "Building as %username%"
  - automated_build/msbuild_vsprojects.bat nios -no-pause
  artifacts:
    when: always
    expire_in: 1 month
    name: "%CI_COMMIT_REF_SLUG%_%CI_COMMIT_SHA%_NIOS"
    paths:
     - bin/*
     - automated_build/log/*

buildkeil:
  stage: build
  variables:
  script:
  - echo "(Keil) Building git branch "%CI_COMMIT_REF_NAME%" at commit "%CI_COMMIT_SHA%" short %CI_COMMIT_SHORT_SHA%"
  - echo "Building as %username%"
  - automated_build/msbuild_vsprojects.bat keil -no-pause
  artifacts:
    when: always
    expire_in: 1 month
    name: "%CI_COMMIT_REF_SLUG%_%CI_COMMIT_SHA%_KEIL"
    paths:
     - bin/*
     - automated_build/log/*

buildother:
  stage: build
  variables:
  script:
  - echo "(Other) Building git branch "%CI_COMMIT_REF_NAME%" at commit "%CI_COMMIT_SHA%" short %CI_COMMIT_SHA%"
  - echo "Building as %username%"
  - automated_build/msbuild_vsprojects.bat other -no-pause
  artifacts:
    when: always
    expire_in: 1 month
    name: "%CI_COMMIT_REF_SLUG%_%CI_COMMIT_SHA%_OTHER"
    paths:
     - bin/*
     - automated_build/log/*

##########
# Deploy #
##########
deploying:
 stage: deploy
 when: on_success
 variables:
   GIT_STRATEGY: none
   TARGETPATH: C:\Users\mouvent\RADEX AG\RX-Project - Documents
 before_script:
    - for /F "tokens=*" %%i in ('powershell Get-Date -Format yyyy.MM.dd.HHmmss') do set DATESTR=%%i
    - echo "The current date is %DATESTR%"
 script:
   - echo %cd%
   - powershell -noprofile -noninteractive -executionpolicy Bypass -command "& '.\automated_build\deploy-mouventprinter.ps1'" -targetpath '%TARGETPATH%' -committag '%CI_COMMIT_TAG%' -buildname '%BUILDNAME%' -commitrefslug '%CI_COMMIT_REF_SLUG%' -commitsha '%CI_COMMIT_SHA%'
