
name: $(Build.BuildId)

pool: 'PrintEngine Pool'


trigger: 
  branches:
    exclude: [release/Release1.0, release/Release1.1, release/Release1.2, release/LB_PrintEngine_Release_1_3_2]

steps:
- task: SonarCloudPrepare@1
  inputs:
    SonarCloud: 'SonarCloud-PE'
    organization: 'mouvent'
    scannerMode: 'CLI'
    configMode: 'file'
  condition:  or(eq(variables['Build.Reason'], 'PullRequest'), eq(variables['Build.SourceBranch'], 'refs/heads/master'))

- script: build-wrapper-win-x86-64.exe  --out-dir  build_wrapper_output_directory python automated_build/build.py 
  displayName: 'Build Print Engine'

- task: PublishBuildArtifacts@1
  inputs:
    PathtoPublish: 'automated_build/log'
    ArtifactName: 'log'
    publishLocation: 'Container'
  condition: always()
  continueOnError: true

- script: automated_build\gitversion /config automated_build\GitVersion.yml /output file /outputfile bin\version.json
    
- task: PublishBuildArtifacts@1
  displayName: 'Publish Artifact: Print Engine'
  inputs:
    ArtifactName: bin
    PathtoPublish: 'bin'
    publishLocation: 'Container'

- script: python -m pytest -c test\pytest.ini --tb=native --junit-xml=TEST-py.xml test
  displayName: 'Run tests'
  
- task: PublishTestResults@2
  inputs:
    testResultsFiles: '**/TEST-*.xml'
    testRunTitle: 'Publish test results'
    failTaskOnFailedTests: true
  condition: succeededOrFailed()

- task: SonarCloudAnalyze@1
  condition:  or(eq(variables['Build.Reason'], 'PullRequest'), eq(variables['Build.SourceBranch'], 'refs/heads/master'))
- task: SonarCloudPublish@1
  inputs:
    pollingTimeoutSec: '300'
  condition:  and(succeeded(), or(eq(variables['Build.Reason'], 'PullRequest'), eq(variables['Build.SourceBranch'], 'refs/heads/master')))