	fluid_board_soc u0 (
		.avalon2fpga_slave_0_s2_writedata                       (<connected-to-avalon2fpga_slave_0_s2_writedata>),                       //                        avalon2fpga_slave_0_s2.writedata
		.avalon2fpga_slave_0_s2_read                            (<connected-to-avalon2fpga_slave_0_s2_read>),                            //                                              .read
		.avalon2fpga_slave_0_s2_write                           (<connected-to-avalon2fpga_slave_0_s2_write>),                           //                                              .write
		.avalon2fpga_slave_0_s2_address                         (<connected-to-avalon2fpga_slave_0_s2_address>),                         //                                              .address
		.avalon2fpga_slave_0_s2_waitrequest                     (<connected-to-avalon2fpga_slave_0_s2_waitrequest>),                     //                                              .waitrequest
		.avalon2fpga_slave_0_s2_readdata                        (<connected-to-avalon2fpga_slave_0_s2_readdata>),                        //                                              .readdata
		.avalon_spi_amc7891_1_conduit_end_sclk                  (<connected-to-avalon_spi_amc7891_1_conduit_end_sclk>),                  //              avalon_spi_amc7891_1_conduit_end.sclk
		.avalon_spi_amc7891_1_conduit_end_cs_n                  (<connected-to-avalon_spi_amc7891_1_conduit_end_cs_n>),                  //                                              .cs_n
		.avalon_spi_amc7891_1_conduit_end_sdio                  (<connected-to-avalon_spi_amc7891_1_conduit_end_sdio>),                  //                                              .sdio
		.avalon_spi_amc7891_1_conduit_end_sdo                   (<connected-to-avalon_spi_amc7891_1_conduit_end_sdo>),                   //                                              .sdo
		.avalon_spi_max31865_0_conduit_end_0_drdy_n             (<connected-to-avalon_spi_max31865_0_conduit_end_0_drdy_n>),             //           avalon_spi_max31865_0_conduit_end_0.drdy_n
		.avalon_spi_max31865_0_conduit_end_0_sclk               (<connected-to-avalon_spi_max31865_0_conduit_end_0_sclk>),               //                                              .sclk
		.avalon_spi_max31865_0_conduit_end_0_cs_n               (<connected-to-avalon_spi_max31865_0_conduit_end_0_cs_n>),               //                                              .cs_n
		.avalon_spi_max31865_0_conduit_end_0_sdi                (<connected-to-avalon_spi_max31865_0_conduit_end_0_sdi>),                //                                              .sdi
		.avalon_spi_max31865_0_conduit_end_0_sdo                (<connected-to-avalon_spi_max31865_0_conduit_end_0_sdo>),                //                                              .sdo
		.avalon_spi_max31865_1_conduit_end_0_drdy_n             (<connected-to-avalon_spi_max31865_1_conduit_end_0_drdy_n>),             //           avalon_spi_max31865_1_conduit_end_0.drdy_n
		.avalon_spi_max31865_1_conduit_end_0_sclk               (<connected-to-avalon_spi_max31865_1_conduit_end_0_sclk>),               //                                              .sclk
		.avalon_spi_max31865_1_conduit_end_0_cs_n               (<connected-to-avalon_spi_max31865_1_conduit_end_0_cs_n>),               //                                              .cs_n
		.avalon_spi_max31865_1_conduit_end_0_sdi                (<connected-to-avalon_spi_max31865_1_conduit_end_0_sdi>),                //                                              .sdi
		.avalon_spi_max31865_1_conduit_end_0_sdo                (<connected-to-avalon_spi_max31865_1_conduit_end_0_sdo>),                //                                              .sdo
		.avalon_spi_max31865_2_conduit_end_0_drdy_n             (<connected-to-avalon_spi_max31865_2_conduit_end_0_drdy_n>),             //           avalon_spi_max31865_2_conduit_end_0.drdy_n
		.avalon_spi_max31865_2_conduit_end_0_sclk               (<connected-to-avalon_spi_max31865_2_conduit_end_0_sclk>),               //                                              .sclk
		.avalon_spi_max31865_2_conduit_end_0_cs_n               (<connected-to-avalon_spi_max31865_2_conduit_end_0_cs_n>),               //                                              .cs_n
		.avalon_spi_max31865_2_conduit_end_0_sdi                (<connected-to-avalon_spi_max31865_2_conduit_end_0_sdi>),                //                                              .sdi
		.avalon_spi_max31865_2_conduit_end_0_sdo                (<connected-to-avalon_spi_max31865_2_conduit_end_0_sdo>),                //                                              .sdo
		.avalon_spi_max31865_3_conduit_end_0_drdy_n             (<connected-to-avalon_spi_max31865_3_conduit_end_0_drdy_n>),             //           avalon_spi_max31865_3_conduit_end_0.drdy_n
		.avalon_spi_max31865_3_conduit_end_0_sclk               (<connected-to-avalon_spi_max31865_3_conduit_end_0_sclk>),               //                                              .sclk
		.avalon_spi_max31865_3_conduit_end_0_cs_n               (<connected-to-avalon_spi_max31865_3_conduit_end_0_cs_n>),               //                                              .cs_n
		.avalon_spi_max31865_3_conduit_end_0_sdi                (<connected-to-avalon_spi_max31865_3_conduit_end_0_sdi>),                //                                              .sdi
		.avalon_spi_max31865_3_conduit_end_0_sdo                (<connected-to-avalon_spi_max31865_3_conduit_end_0_sdo>),                //                                              .sdo
		.avalon_spi_max31865_4_conduit_end_0_drdy_n             (<connected-to-avalon_spi_max31865_4_conduit_end_0_drdy_n>),             //           avalon_spi_max31865_4_conduit_end_0.drdy_n
		.avalon_spi_max31865_4_conduit_end_0_sclk               (<connected-to-avalon_spi_max31865_4_conduit_end_0_sclk>),               //                                              .sclk
		.avalon_spi_max31865_4_conduit_end_0_cs_n               (<connected-to-avalon_spi_max31865_4_conduit_end_0_cs_n>),               //                                              .cs_n
		.avalon_spi_max31865_4_conduit_end_0_sdi                (<connected-to-avalon_spi_max31865_4_conduit_end_0_sdi>),                //                                              .sdi
		.avalon_spi_max31865_4_conduit_end_0_sdo                (<connected-to-avalon_spi_max31865_4_conduit_end_0_sdo>),                //                                              .sdo
		.avalon_spi_max31865_5_conduit_end_0_drdy_n             (<connected-to-avalon_spi_max31865_5_conduit_end_0_drdy_n>),             //           avalon_spi_max31865_5_conduit_end_0.drdy_n
		.avalon_spi_max31865_5_conduit_end_0_sclk               (<connected-to-avalon_spi_max31865_5_conduit_end_0_sclk>),               //                                              .sclk
		.avalon_spi_max31865_5_conduit_end_0_cs_n               (<connected-to-avalon_spi_max31865_5_conduit_end_0_cs_n>),               //                                              .cs_n
		.avalon_spi_max31865_5_conduit_end_0_sdi                (<connected-to-avalon_spi_max31865_5_conduit_end_0_sdi>),                //                                              .sdi
		.avalon_spi_max31865_5_conduit_end_0_sdo                (<connected-to-avalon_spi_max31865_5_conduit_end_0_sdo>),                //                                              .sdo
		.axi_lw_slave_register_0_conduit_end_0_wr_strb          (<connected-to-axi_lw_slave_register_0_conduit_end_0_wr_strb>),          //         axi_lw_slave_register_0_conduit_end_0.wr_strb
		.axi_lw_slave_register_0_conduit_end_0_wr_valid         (<connected-to-axi_lw_slave_register_0_conduit_end_0_wr_valid>),         //                                              .wr_valid
		.axi_lw_slave_register_0_conduit_end_0_rd_addr          (<connected-to-axi_lw_slave_register_0_conduit_end_0_rd_addr>),          //                                              .rd_addr
		.axi_lw_slave_register_0_conduit_end_0_rd_data          (<connected-to-axi_lw_slave_register_0_conduit_end_0_rd_data>),          //                                              .rd_data
		.axi_lw_slave_register_0_conduit_end_0_rd_valid         (<connected-to-axi_lw_slave_register_0_conduit_end_0_rd_valid>),         //                                              .rd_valid
		.axi_lw_slave_register_0_conduit_end_0_rd_ready         (<connected-to-axi_lw_slave_register_0_conduit_end_0_rd_ready>),         //                                              .rd_ready
		.axi_lw_slave_register_0_conduit_end_0_wr_data          (<connected-to-axi_lw_slave_register_0_conduit_end_0_wr_data>),          //                                              .wr_data
		.axi_lw_slave_register_0_conduit_end_0_wr_addr          (<connected-to-axi_lw_slave_register_0_conduit_end_0_wr_addr>),          //                                              .wr_addr
		.flush_pump_pwm_duty_cycle_external_connection_export   (<connected-to-flush_pump_pwm_duty_cycle_external_connection_export>),   // flush_pump_pwm_duty_cycle_external_connection.export
		.flush_pump_pwm_freq_external_connection_export         (<connected-to-flush_pump_pwm_freq_external_connection_export>),         //       flush_pump_pwm_freq_external_connection.export
		.hps_0_uart1_cts                                        (<connected-to-hps_0_uart1_cts>),                                        //                                   hps_0_uart1.cts
		.hps_0_uart1_dsr                                        (<connected-to-hps_0_uart1_dsr>),                                        //                                              .dsr
		.hps_0_uart1_dcd                                        (<connected-to-hps_0_uart1_dcd>),                                        //                                              .dcd
		.hps_0_uart1_ri                                         (<connected-to-hps_0_uart1_ri>),                                         //                                              .ri
		.hps_0_uart1_dtr                                        (<connected-to-hps_0_uart1_dtr>),                                        //                                              .dtr
		.hps_0_uart1_rts                                        (<connected-to-hps_0_uart1_rts>),                                        //                                              .rts
		.hps_0_uart1_out1_n                                     (<connected-to-hps_0_uart1_out1_n>),                                     //                                              .out1_n
		.hps_0_uart1_out2_n                                     (<connected-to-hps_0_uart1_out2_n>),                                     //                                              .out2_n
		.hps_0_uart1_rxd                                        (<connected-to-hps_0_uart1_rxd>),                                        //                                              .rxd
		.hps_0_uart1_txd                                        (<connected-to-hps_0_uart1_txd>),                                        //                                              .txd
		.hps_io_hps_io_emac0_inst_TX_CLK                        (<connected-to-hps_io_hps_io_emac0_inst_TX_CLK>),                        //                                        hps_io.hps_io_emac0_inst_TX_CLK
		.hps_io_hps_io_emac0_inst_TXD0                          (<connected-to-hps_io_hps_io_emac0_inst_TXD0>),                          //                                              .hps_io_emac0_inst_TXD0
		.hps_io_hps_io_emac0_inst_TXD1                          (<connected-to-hps_io_hps_io_emac0_inst_TXD1>),                          //                                              .hps_io_emac0_inst_TXD1
		.hps_io_hps_io_emac0_inst_TXD2                          (<connected-to-hps_io_hps_io_emac0_inst_TXD2>),                          //                                              .hps_io_emac0_inst_TXD2
		.hps_io_hps_io_emac0_inst_TXD3                          (<connected-to-hps_io_hps_io_emac0_inst_TXD3>),                          //                                              .hps_io_emac0_inst_TXD3
		.hps_io_hps_io_emac0_inst_RXD0                          (<connected-to-hps_io_hps_io_emac0_inst_RXD0>),                          //                                              .hps_io_emac0_inst_RXD0
		.hps_io_hps_io_emac0_inst_MDIO                          (<connected-to-hps_io_hps_io_emac0_inst_MDIO>),                          //                                              .hps_io_emac0_inst_MDIO
		.hps_io_hps_io_emac0_inst_MDC                           (<connected-to-hps_io_hps_io_emac0_inst_MDC>),                           //                                              .hps_io_emac0_inst_MDC
		.hps_io_hps_io_emac0_inst_RX_CTL                        (<connected-to-hps_io_hps_io_emac0_inst_RX_CTL>),                        //                                              .hps_io_emac0_inst_RX_CTL
		.hps_io_hps_io_emac0_inst_TX_CTL                        (<connected-to-hps_io_hps_io_emac0_inst_TX_CTL>),                        //                                              .hps_io_emac0_inst_TX_CTL
		.hps_io_hps_io_emac0_inst_RX_CLK                        (<connected-to-hps_io_hps_io_emac0_inst_RX_CLK>),                        //                                              .hps_io_emac0_inst_RX_CLK
		.hps_io_hps_io_emac0_inst_RXD1                          (<connected-to-hps_io_hps_io_emac0_inst_RXD1>),                          //                                              .hps_io_emac0_inst_RXD1
		.hps_io_hps_io_emac0_inst_RXD2                          (<connected-to-hps_io_hps_io_emac0_inst_RXD2>),                          //                                              .hps_io_emac0_inst_RXD2
		.hps_io_hps_io_emac0_inst_RXD3                          (<connected-to-hps_io_hps_io_emac0_inst_RXD3>),                          //                                              .hps_io_emac0_inst_RXD3
		.hps_io_hps_io_sdio_inst_CMD                            (<connected-to-hps_io_hps_io_sdio_inst_CMD>),                            //                                              .hps_io_sdio_inst_CMD
		.hps_io_hps_io_sdio_inst_D0                             (<connected-to-hps_io_hps_io_sdio_inst_D0>),                             //                                              .hps_io_sdio_inst_D0
		.hps_io_hps_io_sdio_inst_D1                             (<connected-to-hps_io_hps_io_sdio_inst_D1>),                             //                                              .hps_io_sdio_inst_D1
		.hps_io_hps_io_sdio_inst_D4                             (<connected-to-hps_io_hps_io_sdio_inst_D4>),                             //                                              .hps_io_sdio_inst_D4
		.hps_io_hps_io_sdio_inst_D5                             (<connected-to-hps_io_hps_io_sdio_inst_D5>),                             //                                              .hps_io_sdio_inst_D5
		.hps_io_hps_io_sdio_inst_D6                             (<connected-to-hps_io_hps_io_sdio_inst_D6>),                             //                                              .hps_io_sdio_inst_D6
		.hps_io_hps_io_sdio_inst_D7                             (<connected-to-hps_io_hps_io_sdio_inst_D7>),                             //                                              .hps_io_sdio_inst_D7
		.hps_io_hps_io_sdio_inst_CLK                            (<connected-to-hps_io_hps_io_sdio_inst_CLK>),                            //                                              .hps_io_sdio_inst_CLK
		.hps_io_hps_io_sdio_inst_D2                             (<connected-to-hps_io_hps_io_sdio_inst_D2>),                             //                                              .hps_io_sdio_inst_D2
		.hps_io_hps_io_sdio_inst_D3                             (<connected-to-hps_io_hps_io_sdio_inst_D3>),                             //                                              .hps_io_sdio_inst_D3
		.hps_io_hps_io_usb1_inst_D0                             (<connected-to-hps_io_hps_io_usb1_inst_D0>),                             //                                              .hps_io_usb1_inst_D0
		.hps_io_hps_io_usb1_inst_D1                             (<connected-to-hps_io_hps_io_usb1_inst_D1>),                             //                                              .hps_io_usb1_inst_D1
		.hps_io_hps_io_usb1_inst_D2                             (<connected-to-hps_io_hps_io_usb1_inst_D2>),                             //                                              .hps_io_usb1_inst_D2
		.hps_io_hps_io_usb1_inst_D3                             (<connected-to-hps_io_hps_io_usb1_inst_D3>),                             //                                              .hps_io_usb1_inst_D3
		.hps_io_hps_io_usb1_inst_D4                             (<connected-to-hps_io_hps_io_usb1_inst_D4>),                             //                                              .hps_io_usb1_inst_D4
		.hps_io_hps_io_usb1_inst_D5                             (<connected-to-hps_io_hps_io_usb1_inst_D5>),                             //                                              .hps_io_usb1_inst_D5
		.hps_io_hps_io_usb1_inst_D6                             (<connected-to-hps_io_hps_io_usb1_inst_D6>),                             //                                              .hps_io_usb1_inst_D6
		.hps_io_hps_io_usb1_inst_D7                             (<connected-to-hps_io_hps_io_usb1_inst_D7>),                             //                                              .hps_io_usb1_inst_D7
		.hps_io_hps_io_usb1_inst_CLK                            (<connected-to-hps_io_hps_io_usb1_inst_CLK>),                            //                                              .hps_io_usb1_inst_CLK
		.hps_io_hps_io_usb1_inst_STP                            (<connected-to-hps_io_hps_io_usb1_inst_STP>),                            //                                              .hps_io_usb1_inst_STP
		.hps_io_hps_io_usb1_inst_DIR                            (<connected-to-hps_io_hps_io_usb1_inst_DIR>),                            //                                              .hps_io_usb1_inst_DIR
		.hps_io_hps_io_usb1_inst_NXT                            (<connected-to-hps_io_hps_io_usb1_inst_NXT>),                            //                                              .hps_io_usb1_inst_NXT
		.hps_io_hps_io_uart0_inst_RX                            (<connected-to-hps_io_hps_io_uart0_inst_RX>),                            //                                              .hps_io_uart0_inst_RX
		.hps_io_hps_io_uart0_inst_TX                            (<connected-to-hps_io_hps_io_uart0_inst_TX>),                            //                                              .hps_io_uart0_inst_TX
		.hps_io_hps_io_gpio_inst_GPIO37                         (<connected-to-hps_io_hps_io_gpio_inst_GPIO37>),                         //                                              .hps_io_gpio_inst_GPIO37
		.hps_io_hps_io_gpio_inst_GPIO44                         (<connected-to-hps_io_hps_io_gpio_inst_GPIO44>),                         //                                              .hps_io_gpio_inst_GPIO44
		.hps_io_hps_io_gpio_inst_GPIO59                         (<connected-to-hps_io_hps_io_gpio_inst_GPIO59>),                         //                                              .hps_io_gpio_inst_GPIO59
		.i2c_master_d_conduit_end_sda                           (<connected-to-i2c_master_d_conduit_end_sda>),                           //                      i2c_master_d_conduit_end.sda
		.i2c_master_d_conduit_end_scl                           (<connected-to-i2c_master_d_conduit_end_scl>),                           //                                              .scl
		.i2c_master_f_conduit_end_sda                           (<connected-to-i2c_master_f_conduit_end_sda>),                           //                      i2c_master_f_conduit_end.sda
		.i2c_master_f_conduit_end_scl                           (<connected-to-i2c_master_f_conduit_end_scl>),                           //                                              .scl
		.i2c_master_is1_conduit_end_sda                         (<connected-to-i2c_master_is1_conduit_end_sda>),                         //                    i2c_master_is1_conduit_end.sda
		.i2c_master_is1_conduit_end_scl                         (<connected-to-i2c_master_is1_conduit_end_scl>),                         //                                              .scl
		.i2c_master_is2_conduit_end_sda                         (<connected-to-i2c_master_is2_conduit_end_sda>),                         //                    i2c_master_is2_conduit_end.sda
		.i2c_master_is2_conduit_end_scl                         (<connected-to-i2c_master_is2_conduit_end_scl>),                         //                                              .scl
		.i2c_master_is3_conduit_end_sda                         (<connected-to-i2c_master_is3_conduit_end_sda>),                         //                    i2c_master_is3_conduit_end.sda
		.i2c_master_is3_conduit_end_scl                         (<connected-to-i2c_master_is3_conduit_end_scl>),                         //                                              .scl
		.i2c_master_is4_conduit_end_sda                         (<connected-to-i2c_master_is4_conduit_end_sda>),                         //                    i2c_master_is4_conduit_end.sda
		.i2c_master_is4_conduit_end_scl                         (<connected-to-i2c_master_is4_conduit_end_scl>),                         //                                              .scl
		.i2c_master_p_conduit_end_sda                           (<connected-to-i2c_master_p_conduit_end_sda>),                           //                      i2c_master_p_conduit_end.sda
		.i2c_master_p_conduit_end_scl                           (<connected-to-i2c_master_p_conduit_end_scl>),                           //                                              .scl
		.memory_mem_a                                           (<connected-to-memory_mem_a>),                                           //                                        memory.mem_a
		.memory_mem_ba                                          (<connected-to-memory_mem_ba>),                                          //                                              .mem_ba
		.memory_mem_ck                                          (<connected-to-memory_mem_ck>),                                          //                                              .mem_ck
		.memory_mem_ck_n                                        (<connected-to-memory_mem_ck_n>),                                        //                                              .mem_ck_n
		.memory_mem_cke                                         (<connected-to-memory_mem_cke>),                                         //                                              .mem_cke
		.memory_mem_cs_n                                        (<connected-to-memory_mem_cs_n>),                                        //                                              .mem_cs_n
		.memory_mem_ras_n                                       (<connected-to-memory_mem_ras_n>),                                       //                                              .mem_ras_n
		.memory_mem_cas_n                                       (<connected-to-memory_mem_cas_n>),                                       //                                              .mem_cas_n
		.memory_mem_we_n                                        (<connected-to-memory_mem_we_n>),                                        //                                              .mem_we_n
		.memory_mem_reset_n                                     (<connected-to-memory_mem_reset_n>),                                     //                                              .mem_reset_n
		.memory_mem_dq                                          (<connected-to-memory_mem_dq>),                                          //                                              .mem_dq
		.memory_mem_dqs                                         (<connected-to-memory_mem_dqs>),                                         //                                              .mem_dqs
		.memory_mem_dqs_n                                       (<connected-to-memory_mem_dqs_n>),                                       //                                              .mem_dqs_n
		.memory_mem_odt                                         (<connected-to-memory_mem_odt>),                                         //                                              .mem_odt
		.memory_mem_dm                                          (<connected-to-memory_mem_dm>),                                          //                                              .mem_dm
		.memory_oct_rzqin                                       (<connected-to-memory_oct_rzqin>),                                       //                                              .oct_rzqin
		.nios2_qsys_0_cpu_resetrequest_conduit_cpu_resetrequest (<connected-to-nios2_qsys_0_cpu_resetrequest_conduit_cpu_resetrequest>), //         nios2_qsys_0_cpu_resetrequest_conduit.cpu_resetrequest
		.nios2_qsys_0_cpu_resetrequest_conduit_cpu_resettaken   (<connected-to-nios2_qsys_0_cpu_resetrequest_conduit_cpu_resettaken>),   //                                              .cpu_resettaken
		.pio_input_external_connection_export                   (<connected-to-pio_input_external_connection_export>),                   //                 pio_input_external_connection.export
		.pio_output_external_connection_export                  (<connected-to-pio_output_external_connection_export>),                  //                pio_output_external_connection.export
		.pio_reset_nios_external_connection_export              (<connected-to-pio_reset_nios_external_connection_export>),              //            pio_reset_nios_external_connection.export
		.pio_watchdog_cnt_external_connection_export            (<connected-to-pio_watchdog_cnt_external_connection_export>),            //          pio_watchdog_cnt_external_connection.export
		.pio_watchdog_freq_external_connection_export           (<connected-to-pio_watchdog_freq_external_connection_export>),           //         pio_watchdog_freq_external_connection.export
		.pll_0_locked_export                                    (<connected-to-pll_0_locked_export>),                                    //                                  pll_0_locked.export
		.pll_0_refclk_clk                                       (<connected-to-pll_0_refclk_clk>),                                       //                                  pll_0_refclk.clk
		.pll_0_reset_reset                                      (<connected-to-pll_0_reset_reset>),                                      //                                   pll_0_reset.reset
		.pll_0_sys_clk_clk                                      (<connected-to-pll_0_sys_clk_clk>),                                      //                                 pll_0_sys_clk.clk
		.pll_0_sys_reset_reset_n                                (<connected-to-pll_0_sys_reset_reset_n>),                                //                               pll_0_sys_reset.reset_n
		.qsys_reset_reset_n                                     (<connected-to-qsys_reset_reset_n>),                                     //                                    qsys_reset.reset_n
		.uart_cond_external_connection_rxd                      (<connected-to-uart_cond_external_connection_rxd>),                      //                 uart_cond_external_connection.rxd
		.uart_cond_external_connection_txd                      (<connected-to-uart_cond_external_connection_txd>)                       //                                              .txd
	);

