-- fluid_board_soc_sld_hub_controller_system_0_hub_controller.vhd

-- This file was auto-generated from altera_streaming_sld_hub_controller_hw.tcl.  If you edit it your changes
-- will probably be lost.
-- 
-- Generated using ACDS version 14.0 200 at 2015.12.23.13:40:21

library IEEE;
use IEEE.std_logic_1164.all;
use IEEE.numeric_std.all;

entity fluid_board_soc_sld_hub_controller_system_0_hub_controller is
	generic (
		ENABLE_JTAG_IO_SELECTION : boolean := false
	);
	port (
		clk_clk              : in  std_logic                    := '0';             --    clk.clk
		reset_reset          : in  std_logic                    := '0';             --  reset.reset
		sink_valid           : in  std_logic                    := '0';             --   sink.valid
		sink_startofpacket   : in  std_logic                    := '0';             --       .startofpacket
		sink_endofpacket     : in  std_logic                    := '0';             --       .endofpacket
		sink_data            : in  std_logic_vector(7 downto 0) := (others => '0'); --       .data
		sink_ready           : out std_logic;                                       --       .ready
		source_valid         : out std_logic;                                       -- source.valid
		source_startofpacket : out std_logic;                                       --       .startofpacket
		source_endofpacket   : out std_logic;                                       --       .endofpacket
		source_data          : out std_logic_vector(7 downto 0);                    --       .data
		source_ready         : in  std_logic                    := '0'              --       .ready
	);
end entity fluid_board_soc_sld_hub_controller_system_0_hub_controller;

architecture rtl of fluid_board_soc_sld_hub_controller_system_0_hub_controller is
	component altera_streaming_sld_hub_controller_core is
		port (
			clk        : in  std_logic                    := 'X';             -- clk
			reset      : in  std_logic                    := 'X';             -- reset
			cmd_valid  : in  std_logic                    := 'X';             -- valid
			cmd_sop    : in  std_logic                    := 'X';             -- startofpacket
			cmd_eop    : in  std_logic                    := 'X';             -- endofpacket
			cmd_data   : in  std_logic_vector(7 downto 0) := (others => 'X'); -- data
			cmd_ready  : out std_logic;                                       -- ready
			resp_valid : out std_logic;                                       -- valid
			resp_sop   : out std_logic;                                       -- startofpacket
			resp_eop   : out std_logic;                                       -- endofpacket
			resp_data  : out std_logic_vector(7 downto 0);                    -- data
			resp_ready : in  std_logic                    := 'X'              -- ready
		);
	end component altera_streaming_sld_hub_controller_core;

begin

	enable_jtag_io_selection_check : if ENABLE_JTAG_IO_SELECTION /= false generate
		assert false report "Supplied generics do not match expected generics" severity Failure;
	end generate;

	core : component altera_streaming_sld_hub_controller_core
		port map (
			clk        => clk_clk,              --    clk.clk
			reset      => reset_reset,          --  reset.reset
			cmd_valid  => sink_valid,           --   sink.valid
			cmd_sop    => sink_startofpacket,   --       .startofpacket
			cmd_eop    => sink_endofpacket,     --       .endofpacket
			cmd_data   => sink_data,            --       .data
			cmd_ready  => sink_ready,           --       .ready
			resp_valid => source_valid,         -- source.valid
			resp_sop   => source_startofpacket, --       .startofpacket
			resp_eop   => source_endofpacket,   --       .endofpacket
			resp_data  => source_data,          --       .data
			resp_ready => source_ready          --       .ready
		);

end architecture rtl; -- of fluid_board_soc_sld_hub_controller_system_0_hub_controller
