--IP Functional Simulation Model
--VERSION_BEGIN 14.0 cbx_mgl 2014:06:17:18:10:38:SJ cbx_simgen 2014:06:17:18:06:03:SJ  VERSION_END


-- Copyright (C) 1991-2014 Altera Corporation. All rights reserved.
-- Your use of Altera Corporation's design tools, logic functions 
-- and other software and tools, and its AMPP partner logic 
-- functions, and any output files from any of the foregoing 
-- (including device programming or simulation files), and any 
-- associated documentation or information are expressly subject 
-- to the terms and conditions of the Altera Program License 
-- Subscription Agreement, the Altera Quartus II License Agreement,
-- the Altera MegaCore Function License Agreement, or other 
-- applicable license agreement, including, without limitation, 
-- that your use is for the sole purpose of programming logic 
-- devices manufactured by Altera and sold by Altera or its 
-- authorized distributors.  Please refer to the applicable 
-- agreement for further details.

-- You may only use these simulation model output files for simulation
-- purposes and expressly not for synthesis or any other purposes (in which
-- event Altera disclaims all warranties of any kind).


--synopsys translate_off

--synthesis_resources = lut 22 mux21 25 
 LIBRARY ieee;
 USE ieee.std_logic_1164.all;

 ENTITY  fluid_board_soc_mm_interconnect_0_i2c_master_is1_avalon_slave_0_agent_rdata_fifo IS 
	 PORT 
	 ( 
		 clk	:	IN  STD_LOGIC;
		 in_data	:	IN  STD_LOGIC_VECTOR (9 DOWNTO 0);
		 in_ready	:	OUT  STD_LOGIC;
		 in_valid	:	IN  STD_LOGIC;
		 out_data	:	OUT  STD_LOGIC_VECTOR (9 DOWNTO 0);
		 out_ready	:	IN  STD_LOGIC;
		 out_valid	:	OUT  STD_LOGIC;
		 reset	:	IN  STD_LOGIC
	 ); 
 END fluid_board_soc_mm_interconnect_0_i2c_master_is1_avalon_slave_0_agent_rdata_fifo;

 ARCHITECTURE RTL OF fluid_board_soc_mm_interconnect_0_i2c_master_is1_avalon_slave_0_agent_rdata_fifo IS

	 ATTRIBUTE synthesis_clearbox : natural;
	 ATTRIBUTE synthesis_clearbox OF RTL : ARCHITECTURE IS 1;
	 SIGNAL	fluid_board_soc_mm_interconnect_0_i2c_master_is1_avalon_slave_0_agent_rdata_fifo_altera_avalon_sc_fifo_i2c_master_is1_avalon_slave_0_agent_rdata_fifo_mem_1_0_75q	:	STD_LOGIC := '0';
	 SIGNAL	fluid_board_soc_mm_interconnect_0_i2c_master_is1_avalon_slave_0_agent_rdata_fifo_altera_avalon_sc_fifo_i2c_master_is1_avalon_slave_0_agent_rdata_fifo_mem_1_1_67q	:	STD_LOGIC := '0';
	 SIGNAL	fluid_board_soc_mm_interconnect_0_i2c_master_is1_avalon_slave_0_agent_rdata_fifo_altera_avalon_sc_fifo_i2c_master_is1_avalon_slave_0_agent_rdata_fifo_mem_1_2_66q	:	STD_LOGIC := '0';
	 SIGNAL	fluid_board_soc_mm_interconnect_0_i2c_master_is1_avalon_slave_0_agent_rdata_fifo_altera_avalon_sc_fifo_i2c_master_is1_avalon_slave_0_agent_rdata_fifo_mem_1_3_65q	:	STD_LOGIC := '0';
	 SIGNAL	fluid_board_soc_mm_interconnect_0_i2c_master_is1_avalon_slave_0_agent_rdata_fifo_altera_avalon_sc_fifo_i2c_master_is1_avalon_slave_0_agent_rdata_fifo_mem_1_4_64q	:	STD_LOGIC := '0';
	 SIGNAL	fluid_board_soc_mm_interconnect_0_i2c_master_is1_avalon_slave_0_agent_rdata_fifo_altera_avalon_sc_fifo_i2c_master_is1_avalon_slave_0_agent_rdata_fifo_mem_1_5_63q	:	STD_LOGIC := '0';
	 SIGNAL	fluid_board_soc_mm_interconnect_0_i2c_master_is1_avalon_slave_0_agent_rdata_fifo_altera_avalon_sc_fifo_i2c_master_is1_avalon_slave_0_agent_rdata_fifo_mem_1_6_62q	:	STD_LOGIC := '0';
	 SIGNAL	fluid_board_soc_mm_interconnect_0_i2c_master_is1_avalon_slave_0_agent_rdata_fifo_altera_avalon_sc_fifo_i2c_master_is1_avalon_slave_0_agent_rdata_fifo_mem_1_7_61q	:	STD_LOGIC := '0';
	 SIGNAL	fluid_board_soc_mm_interconnect_0_i2c_master_is1_avalon_slave_0_agent_rdata_fifo_altera_avalon_sc_fifo_i2c_master_is1_avalon_slave_0_agent_rdata_fifo_mem_1_8_60q	:	STD_LOGIC := '0';
	 SIGNAL	fluid_board_soc_mm_interconnect_0_i2c_master_is1_avalon_slave_0_agent_rdata_fifo_altera_avalon_sc_fifo_i2c_master_is1_avalon_slave_0_agent_rdata_fifo_mem_1_9_59q	:	STD_LOGIC := '0';
	 SIGNAL	fluid_board_soc_mm_interconnect_0_i2c_master_is1_avalon_slave_0_agent_rdata_fifo_altera_avalon_sc_fifo_i2c_master_is1_avalon_slave_0_agent_rdata_fifo_mem_used_0_78q	:	STD_LOGIC := '0';
	 SIGNAL	fluid_board_soc_mm_interconnect_0_i2c_master_is1_avalon_slave_0_agent_rdata_fifo_altera_avalon_sc_fifo_i2c_master_is1_avalon_slave_0_agent_rdata_fifo_mem_used_1_131q	:	STD_LOGIC := '0';
	 SIGNAL  wire_nl_w14w	:	STD_LOGIC_VECTOR (0 DOWNTO 0);
	 SIGNAL  wire_nl_w1w	:	STD_LOGIC_VECTOR (0 DOWNTO 0);
	 SIGNAL	fluid_board_soc_mm_interconnect_0_i2c_master_is1_avalon_slave_0_agent_rdata_fifo_altera_avalon_sc_fifo_i2c_master_is1_avalon_slave_0_agent_rdata_fifo_mem_0_0_58q	:	STD_LOGIC := '0';
	 SIGNAL	fluid_board_soc_mm_interconnect_0_i2c_master_is1_avalon_slave_0_agent_rdata_fifo_altera_avalon_sc_fifo_i2c_master_is1_avalon_slave_0_agent_rdata_fifo_mem_0_1_57q	:	STD_LOGIC := '0';
	 SIGNAL	fluid_board_soc_mm_interconnect_0_i2c_master_is1_avalon_slave_0_agent_rdata_fifo_altera_avalon_sc_fifo_i2c_master_is1_avalon_slave_0_agent_rdata_fifo_mem_0_2_56q	:	STD_LOGIC := '0';
	 SIGNAL	fluid_board_soc_mm_interconnect_0_i2c_master_is1_avalon_slave_0_agent_rdata_fifo_altera_avalon_sc_fifo_i2c_master_is1_avalon_slave_0_agent_rdata_fifo_mem_0_3_55q	:	STD_LOGIC := '0';
	 SIGNAL	fluid_board_soc_mm_interconnect_0_i2c_master_is1_avalon_slave_0_agent_rdata_fifo_altera_avalon_sc_fifo_i2c_master_is1_avalon_slave_0_agent_rdata_fifo_mem_0_4_54q	:	STD_LOGIC := '0';
	 SIGNAL	fluid_board_soc_mm_interconnect_0_i2c_master_is1_avalon_slave_0_agent_rdata_fifo_altera_avalon_sc_fifo_i2c_master_is1_avalon_slave_0_agent_rdata_fifo_mem_0_5_53q	:	STD_LOGIC := '0';
	 SIGNAL	fluid_board_soc_mm_interconnect_0_i2c_master_is1_avalon_slave_0_agent_rdata_fifo_altera_avalon_sc_fifo_i2c_master_is1_avalon_slave_0_agent_rdata_fifo_mem_0_6_52q	:	STD_LOGIC := '0';
	 SIGNAL	fluid_board_soc_mm_interconnect_0_i2c_master_is1_avalon_slave_0_agent_rdata_fifo_altera_avalon_sc_fifo_i2c_master_is1_avalon_slave_0_agent_rdata_fifo_mem_0_7_51q	:	STD_LOGIC := '0';
	 SIGNAL	fluid_board_soc_mm_interconnect_0_i2c_master_is1_avalon_slave_0_agent_rdata_fifo_altera_avalon_sc_fifo_i2c_master_is1_avalon_slave_0_agent_rdata_fifo_mem_0_8_50q	:	STD_LOGIC := '0';
	 SIGNAL	fluid_board_soc_mm_interconnect_0_i2c_master_is1_avalon_slave_0_agent_rdata_fifo_altera_avalon_sc_fifo_i2c_master_is1_avalon_slave_0_agent_rdata_fifo_mem_0_9_49q	:	STD_LOGIC := '0';
	 SIGNAL	wire_fluid_board_soc_mm_interconnect_0_i2c_master_is1_avalon_slave_0_agent_rdata_fifo_altera_avalon_sc_fifo_i2c_master_is1_avalon_slave_0_agent_rdata_fifo_mem_29m_dataout	:	STD_LOGIC;
	 SIGNAL	wire_fluid_board_soc_mm_interconnect_0_i2c_master_is1_avalon_slave_0_agent_rdata_fifo_altera_avalon_sc_fifo_i2c_master_is1_avalon_slave_0_agent_rdata_fifo_mem_30m_dataout	:	STD_LOGIC;
	 SIGNAL	wire_fluid_board_soc_mm_interconnect_0_i2c_master_is1_avalon_slave_0_agent_rdata_fifo_altera_avalon_sc_fifo_i2c_master_is1_avalon_slave_0_agent_rdata_fifo_mem_31m_dataout	:	STD_LOGIC;
	 SIGNAL	wire_fluid_board_soc_mm_interconnect_0_i2c_master_is1_avalon_slave_0_agent_rdata_fifo_altera_avalon_sc_fifo_i2c_master_is1_avalon_slave_0_agent_rdata_fifo_mem_32m_dataout	:	STD_LOGIC;
	 SIGNAL	wire_fluid_board_soc_mm_interconnect_0_i2c_master_is1_avalon_slave_0_agent_rdata_fifo_altera_avalon_sc_fifo_i2c_master_is1_avalon_slave_0_agent_rdata_fifo_mem_33m_dataout	:	STD_LOGIC;
	 SIGNAL	wire_fluid_board_soc_mm_interconnect_0_i2c_master_is1_avalon_slave_0_agent_rdata_fifo_altera_avalon_sc_fifo_i2c_master_is1_avalon_slave_0_agent_rdata_fifo_mem_34m_dataout	:	STD_LOGIC;
	 SIGNAL	wire_fluid_board_soc_mm_interconnect_0_i2c_master_is1_avalon_slave_0_agent_rdata_fifo_altera_avalon_sc_fifo_i2c_master_is1_avalon_slave_0_agent_rdata_fifo_mem_35m_dataout	:	STD_LOGIC;
	 SIGNAL	wire_fluid_board_soc_mm_interconnect_0_i2c_master_is1_avalon_slave_0_agent_rdata_fifo_altera_avalon_sc_fifo_i2c_master_is1_avalon_slave_0_agent_rdata_fifo_mem_36m_dataout	:	STD_LOGIC;
	 SIGNAL	wire_fluid_board_soc_mm_interconnect_0_i2c_master_is1_avalon_slave_0_agent_rdata_fifo_altera_avalon_sc_fifo_i2c_master_is1_avalon_slave_0_agent_rdata_fifo_mem_37m_dataout	:	STD_LOGIC;
	 SIGNAL	wire_fluid_board_soc_mm_interconnect_0_i2c_master_is1_avalon_slave_0_agent_rdata_fifo_altera_avalon_sc_fifo_i2c_master_is1_avalon_slave_0_agent_rdata_fifo_mem_38m_dataout	:	STD_LOGIC;
	 SIGNAL	wire_fluid_board_soc_mm_interconnect_0_i2c_master_is1_avalon_slave_0_agent_rdata_fifo_altera_avalon_sc_fifo_i2c_master_is1_avalon_slave_0_agent_rdata_fifo_mem_used_0_269m_dataout	:	STD_LOGIC;
	 SIGNAL	wire_fluid_board_soc_mm_interconnect_0_i2c_master_is1_avalon_slave_0_agent_rdata_fifo_altera_avalon_sc_fifo_i2c_master_is1_avalon_slave_0_agent_rdata_fifo_mem_used_1_270m_dataout	:	STD_LOGIC;
	 SIGNAL	wire_fluid_board_soc_mm_interconnect_0_i2c_master_is1_avalon_slave_0_agent_rdata_fifo_altera_avalon_sc_fifo_i2c_master_is1_avalon_slave_0_agent_rdata_fifo_mem_used_72m_dataout	:	STD_LOGIC;
	 SIGNAL	wire_fluid_board_soc_mm_interconnect_0_i2c_master_is1_avalon_slave_0_agent_rdata_fifo_altera_avalon_sc_fifo_i2c_master_is1_avalon_slave_0_agent_rdata_fifo_mem_used_73m_dataout	:	STD_LOGIC;
	 SIGNAL	wire_fluid_board_soc_mm_interconnect_0_i2c_master_is1_avalon_slave_0_agent_rdata_fifo_altera_avalon_sc_fifo_i2c_master_is1_avalon_slave_0_agent_rdata_fifo_mem_used_76m_dataout	:	STD_LOGIC;
	 SIGNAL	wire_fluid_board_soc_mm_interconnect_0_i2c_master_is1_avalon_slave_0_agent_rdata_fifo_altera_avalon_sc_fifo_i2c_master_is1_avalon_slave_0_agent_rdata_fifo_out_data_0_93m_dataout	:	STD_LOGIC;
	 SIGNAL	wire_fluid_board_soc_mm_interconnect_0_i2c_master_is1_avalon_slave_0_agent_rdata_fifo_altera_avalon_sc_fifo_i2c_master_is1_avalon_slave_0_agent_rdata_fifo_out_data_1_92m_dataout	:	STD_LOGIC;
	 SIGNAL	wire_fluid_board_soc_mm_interconnect_0_i2c_master_is1_avalon_slave_0_agent_rdata_fifo_altera_avalon_sc_fifo_i2c_master_is1_avalon_slave_0_agent_rdata_fifo_out_data_2_91m_dataout	:	STD_LOGIC;
	 SIGNAL	wire_fluid_board_soc_mm_interconnect_0_i2c_master_is1_avalon_slave_0_agent_rdata_fifo_altera_avalon_sc_fifo_i2c_master_is1_avalon_slave_0_agent_rdata_fifo_out_data_3_90m_dataout	:	STD_LOGIC;
	 SIGNAL	wire_fluid_board_soc_mm_interconnect_0_i2c_master_is1_avalon_slave_0_agent_rdata_fifo_altera_avalon_sc_fifo_i2c_master_is1_avalon_slave_0_agent_rdata_fifo_out_data_4_89m_dataout	:	STD_LOGIC;
	 SIGNAL	wire_fluid_board_soc_mm_interconnect_0_i2c_master_is1_avalon_slave_0_agent_rdata_fifo_altera_avalon_sc_fifo_i2c_master_is1_avalon_slave_0_agent_rdata_fifo_out_data_5_88m_dataout	:	STD_LOGIC;
	 SIGNAL	wire_fluid_board_soc_mm_interconnect_0_i2c_master_is1_avalon_slave_0_agent_rdata_fifo_altera_avalon_sc_fifo_i2c_master_is1_avalon_slave_0_agent_rdata_fifo_out_data_6_87m_dataout	:	STD_LOGIC;
	 SIGNAL	wire_fluid_board_soc_mm_interconnect_0_i2c_master_is1_avalon_slave_0_agent_rdata_fifo_altera_avalon_sc_fifo_i2c_master_is1_avalon_slave_0_agent_rdata_fifo_out_data_7_86m_dataout	:	STD_LOGIC;
	 SIGNAL	wire_fluid_board_soc_mm_interconnect_0_i2c_master_is1_avalon_slave_0_agent_rdata_fifo_altera_avalon_sc_fifo_i2c_master_is1_avalon_slave_0_agent_rdata_fifo_out_data_8_85m_dataout	:	STD_LOGIC;
	 SIGNAL	wire_fluid_board_soc_mm_interconnect_0_i2c_master_is1_avalon_slave_0_agent_rdata_fifo_altera_avalon_sc_fifo_i2c_master_is1_avalon_slave_0_agent_rdata_fifo_out_data_9_84m_dataout	:	STD_LOGIC;
	 SIGNAL  wire_w_lg_in_valid31w	:	STD_LOGIC_VECTOR (0 DOWNTO 0);
	 SIGNAL  wire_w_lg_reset26w	:	STD_LOGIC_VECTOR (0 DOWNTO 0);
	 SIGNAL  wire_w13w	:	STD_LOGIC_VECTOR (0 DOWNTO 0);
	 SIGNAL  s_wire_fluid_board_soc_mm_interconnect_0_i2c_master_is1_avalon_slave_0_agent_rdata_fifo_altera_avalon_sc_fifo_i2c_master_is1_avalon_slave_0_agent_rdata_fifo_always0_28_dataout :	STD_LOGIC;
	 SIGNAL  s_wire_fluid_board_soc_mm_interconnect_0_i2c_master_is1_avalon_slave_0_agent_rdata_fifo_altera_avalon_sc_fifo_i2c_master_is1_avalon_slave_0_agent_rdata_fifo_always2_71_dataout :	STD_LOGIC;
	 SIGNAL  s_wire_fluid_board_soc_mm_interconnect_0_i2c_master_is1_avalon_slave_0_agent_rdata_fifo_altera_avalon_sc_fifo_i2c_master_is1_avalon_slave_0_agent_rdata_fifo_always4_83_dataout :	STD_LOGIC;
	 SIGNAL  s_wire_fluid_board_soc_mm_interconnect_0_i2c_master_is1_avalon_slave_0_agent_rdata_fifo_altera_avalon_sc_fifo_i2c_master_is1_avalon_slave_0_agent_rdata_fifo_empty_81_dataout :	STD_LOGIC;
	 SIGNAL  s_wire_fluid_board_soc_mm_interconnect_0_i2c_master_is1_avalon_slave_0_agent_rdata_fifo_altera_avalon_sc_fifo_i2c_master_is1_avalon_slave_0_agent_rdata_fifo_read_68_dataout :	STD_LOGIC;
	 SIGNAL  s_wire_fluid_board_soc_mm_interconnect_0_i2c_master_is1_avalon_slave_0_agent_rdata_fifo_altera_avalon_sc_fifo_i2c_master_is1_avalon_slave_0_agent_rdata_fifo_write_70_dataout :	STD_LOGIC;
	 SIGNAL  s_wire_vcc :	STD_LOGIC;
 BEGIN

	wire_w_lg_in_valid31w(0) <= NOT in_valid;
	wire_w_lg_reset26w(0) <= NOT reset;
	wire_w13w(0) <= NOT s_wire_fluid_board_soc_mm_interconnect_0_i2c_master_is1_avalon_slave_0_agent_rdata_fifo_altera_avalon_sc_fifo_i2c_master_is1_avalon_slave_0_agent_rdata_fifo_empty_81_dataout;
	in_ready <= wire_nl_w1w(0);
	out_data <= ( wire_fluid_board_soc_mm_interconnect_0_i2c_master_is1_avalon_slave_0_agent_rdata_fifo_altera_avalon_sc_fifo_i2c_master_is1_avalon_slave_0_agent_rdata_fifo_out_data_9_84m_dataout & wire_fluid_board_soc_mm_interconnect_0_i2c_master_is1_avalon_slave_0_agent_rdata_fifo_altera_avalon_sc_fifo_i2c_master_is1_avalon_slave_0_agent_rdata_fifo_out_data_8_85m_dataout & wire_fluid_board_soc_mm_interconnect_0_i2c_master_is1_avalon_slave_0_agent_rdata_fifo_altera_avalon_sc_fifo_i2c_master_is1_avalon_slave_0_agent_rdata_fifo_out_data_7_86m_dataout & wire_fluid_board_soc_mm_interconnect_0_i2c_master_is1_avalon_slave_0_agent_rdata_fifo_altera_avalon_sc_fifo_i2c_master_is1_avalon_slave_0_agent_rdata_fifo_out_data_6_87m_dataout & wire_fluid_board_soc_mm_interconnect_0_i2c_master_is1_avalon_slave_0_agent_rdata_fifo_altera_avalon_sc_fifo_i2c_master_is1_avalon_slave_0_agent_rdata_fifo_out_data_5_88m_dataout & wire_fluid_board_soc_mm_interconnect_0_i2c_master_is1_avalon_slave_0_agent_rdata_fifo_altera_avalon_sc_fifo_i2c_master_is1_avalon_slave_0_agent_rdata_fifo_out_data_4_89m_dataout & wire_fluid_board_soc_mm_interconnect_0_i2c_master_is1_avalon_slave_0_agent_rdata_fifo_altera_avalon_sc_fifo_i2c_master_is1_avalon_slave_0_agent_rdata_fifo_out_data_3_90m_dataout & wire_fluid_board_soc_mm_interconnect_0_i2c_master_is1_avalon_slave_0_agent_rdata_fifo_altera_avalon_sc_fifo_i2c_master_is1_avalon_slave_0_agent_rdata_fifo_out_data_2_91m_dataout & wire_fluid_board_soc_mm_interconnect_0_i2c_master_is1_avalon_slave_0_agent_rdata_fifo_altera_avalon_sc_fifo_i2c_master_is1_avalon_slave_0_agent_rdata_fifo_out_data_1_92m_dataout & wire_fluid_board_soc_mm_interconnect_0_i2c_master_is1_avalon_slave_0_agent_rdata_fifo_altera_avalon_sc_fifo_i2c_master_is1_avalon_slave_0_agent_rdata_fifo_out_data_0_93m_dataout);
	out_valid <= wire_w13w(0);
	s_wire_fluid_board_soc_mm_interconnect_0_i2c_master_is1_avalon_slave_0_agent_rdata_fifo_altera_avalon_sc_fifo_i2c_master_is1_avalon_slave_0_agent_rdata_fifo_always0_28_dataout <= (s_wire_fluid_board_soc_mm_interconnect_0_i2c_master_is1_avalon_slave_0_agent_rdata_fifo_altera_avalon_sc_fifo_i2c_master_is1_avalon_slave_0_agent_rdata_fifo_read_68_dataout OR wire_nl_w14w(0));
	s_wire_fluid_board_soc_mm_interconnect_0_i2c_master_is1_avalon_slave_0_agent_rdata_fifo_altera_avalon_sc_fifo_i2c_master_is1_avalon_slave_0_agent_rdata_fifo_always2_71_dataout <= (s_wire_fluid_board_soc_mm_interconnect_0_i2c_master_is1_avalon_slave_0_agent_rdata_fifo_altera_avalon_sc_fifo_i2c_master_is1_avalon_slave_0_agent_rdata_fifo_read_68_dataout XOR s_wire_fluid_board_soc_mm_interconnect_0_i2c_master_is1_avalon_slave_0_agent_rdata_fifo_altera_avalon_sc_fifo_i2c_master_is1_avalon_slave_0_agent_rdata_fifo_write_70_dataout);
	s_wire_fluid_board_soc_mm_interconnect_0_i2c_master_is1_avalon_slave_0_agent_rdata_fifo_altera_avalon_sc_fifo_i2c_master_is1_avalon_slave_0_agent_rdata_fifo_always4_83_dataout <= (in_valid AND wire_nl_w14w(0));
	s_wire_fluid_board_soc_mm_interconnect_0_i2c_master_is1_avalon_slave_0_agent_rdata_fifo_altera_avalon_sc_fifo_i2c_master_is1_avalon_slave_0_agent_rdata_fifo_empty_81_dataout <= (wire_w_lg_in_valid31w(0) AND wire_nl_w14w(0));
	s_wire_fluid_board_soc_mm_interconnect_0_i2c_master_is1_avalon_slave_0_agent_rdata_fifo_altera_avalon_sc_fifo_i2c_master_is1_avalon_slave_0_agent_rdata_fifo_read_68_dataout <= (wire_w13w(0) AND (out_ready OR s_wire_fluid_board_soc_mm_interconnect_0_i2c_master_is1_avalon_slave_0_agent_rdata_fifo_altera_avalon_sc_fifo_i2c_master_is1_avalon_slave_0_agent_rdata_fifo_empty_81_dataout));
	s_wire_fluid_board_soc_mm_interconnect_0_i2c_master_is1_avalon_slave_0_agent_rdata_fifo_altera_avalon_sc_fifo_i2c_master_is1_avalon_slave_0_agent_rdata_fifo_write_70_dataout <= (in_valid AND wire_nl_w1w(0));
	s_wire_vcc <= '1';
	PROCESS (clk, reset)
	BEGIN
		IF (reset = '1') THEN
				fluid_board_soc_mm_interconnect_0_i2c_master_is1_avalon_slave_0_agent_rdata_fifo_altera_avalon_sc_fifo_i2c_master_is1_avalon_slave_0_agent_rdata_fifo_mem_1_0_75q <= '0';
				fluid_board_soc_mm_interconnect_0_i2c_master_is1_avalon_slave_0_agent_rdata_fifo_altera_avalon_sc_fifo_i2c_master_is1_avalon_slave_0_agent_rdata_fifo_mem_1_1_67q <= '0';
				fluid_board_soc_mm_interconnect_0_i2c_master_is1_avalon_slave_0_agent_rdata_fifo_altera_avalon_sc_fifo_i2c_master_is1_avalon_slave_0_agent_rdata_fifo_mem_1_2_66q <= '0';
				fluid_board_soc_mm_interconnect_0_i2c_master_is1_avalon_slave_0_agent_rdata_fifo_altera_avalon_sc_fifo_i2c_master_is1_avalon_slave_0_agent_rdata_fifo_mem_1_3_65q <= '0';
				fluid_board_soc_mm_interconnect_0_i2c_master_is1_avalon_slave_0_agent_rdata_fifo_altera_avalon_sc_fifo_i2c_master_is1_avalon_slave_0_agent_rdata_fifo_mem_1_4_64q <= '0';
				fluid_board_soc_mm_interconnect_0_i2c_master_is1_avalon_slave_0_agent_rdata_fifo_altera_avalon_sc_fifo_i2c_master_is1_avalon_slave_0_agent_rdata_fifo_mem_1_5_63q <= '0';
				fluid_board_soc_mm_interconnect_0_i2c_master_is1_avalon_slave_0_agent_rdata_fifo_altera_avalon_sc_fifo_i2c_master_is1_avalon_slave_0_agent_rdata_fifo_mem_1_6_62q <= '0';
				fluid_board_soc_mm_interconnect_0_i2c_master_is1_avalon_slave_0_agent_rdata_fifo_altera_avalon_sc_fifo_i2c_master_is1_avalon_slave_0_agent_rdata_fifo_mem_1_7_61q <= '0';
				fluid_board_soc_mm_interconnect_0_i2c_master_is1_avalon_slave_0_agent_rdata_fifo_altera_avalon_sc_fifo_i2c_master_is1_avalon_slave_0_agent_rdata_fifo_mem_1_8_60q <= '0';
				fluid_board_soc_mm_interconnect_0_i2c_master_is1_avalon_slave_0_agent_rdata_fifo_altera_avalon_sc_fifo_i2c_master_is1_avalon_slave_0_agent_rdata_fifo_mem_1_9_59q <= '0';
				fluid_board_soc_mm_interconnect_0_i2c_master_is1_avalon_slave_0_agent_rdata_fifo_altera_avalon_sc_fifo_i2c_master_is1_avalon_slave_0_agent_rdata_fifo_mem_used_0_78q <= '0';
				fluid_board_soc_mm_interconnect_0_i2c_master_is1_avalon_slave_0_agent_rdata_fifo_altera_avalon_sc_fifo_i2c_master_is1_avalon_slave_0_agent_rdata_fifo_mem_used_1_131q <= '0';
		ELSIF (clk = '1' AND clk'event) THEN
				fluid_board_soc_mm_interconnect_0_i2c_master_is1_avalon_slave_0_agent_rdata_fifo_altera_avalon_sc_fifo_i2c_master_is1_avalon_slave_0_agent_rdata_fifo_mem_1_0_75q <= wire_fluid_board_soc_mm_interconnect_0_i2c_master_is1_avalon_slave_0_agent_rdata_fifo_altera_avalon_sc_fifo_i2c_master_is1_avalon_slave_0_agent_rdata_fifo_mem_38m_dataout;
				fluid_board_soc_mm_interconnect_0_i2c_master_is1_avalon_slave_0_agent_rdata_fifo_altera_avalon_sc_fifo_i2c_master_is1_avalon_slave_0_agent_rdata_fifo_mem_1_1_67q <= wire_fluid_board_soc_mm_interconnect_0_i2c_master_is1_avalon_slave_0_agent_rdata_fifo_altera_avalon_sc_fifo_i2c_master_is1_avalon_slave_0_agent_rdata_fifo_mem_37m_dataout;
				fluid_board_soc_mm_interconnect_0_i2c_master_is1_avalon_slave_0_agent_rdata_fifo_altera_avalon_sc_fifo_i2c_master_is1_avalon_slave_0_agent_rdata_fifo_mem_1_2_66q <= wire_fluid_board_soc_mm_interconnect_0_i2c_master_is1_avalon_slave_0_agent_rdata_fifo_altera_avalon_sc_fifo_i2c_master_is1_avalon_slave_0_agent_rdata_fifo_mem_36m_dataout;
				fluid_board_soc_mm_interconnect_0_i2c_master_is1_avalon_slave_0_agent_rdata_fifo_altera_avalon_sc_fifo_i2c_master_is1_avalon_slave_0_agent_rdata_fifo_mem_1_3_65q <= wire_fluid_board_soc_mm_interconnect_0_i2c_master_is1_avalon_slave_0_agent_rdata_fifo_altera_avalon_sc_fifo_i2c_master_is1_avalon_slave_0_agent_rdata_fifo_mem_35m_dataout;
				fluid_board_soc_mm_interconnect_0_i2c_master_is1_avalon_slave_0_agent_rdata_fifo_altera_avalon_sc_fifo_i2c_master_is1_avalon_slave_0_agent_rdata_fifo_mem_1_4_64q <= wire_fluid_board_soc_mm_interconnect_0_i2c_master_is1_avalon_slave_0_agent_rdata_fifo_altera_avalon_sc_fifo_i2c_master_is1_avalon_slave_0_agent_rdata_fifo_mem_34m_dataout;
				fluid_board_soc_mm_interconnect_0_i2c_master_is1_avalon_slave_0_agent_rdata_fifo_altera_avalon_sc_fifo_i2c_master_is1_avalon_slave_0_agent_rdata_fifo_mem_1_5_63q <= wire_fluid_board_soc_mm_interconnect_0_i2c_master_is1_avalon_slave_0_agent_rdata_fifo_altera_avalon_sc_fifo_i2c_master_is1_avalon_slave_0_agent_rdata_fifo_mem_33m_dataout;
				fluid_board_soc_mm_interconnect_0_i2c_master_is1_avalon_slave_0_agent_rdata_fifo_altera_avalon_sc_fifo_i2c_master_is1_avalon_slave_0_agent_rdata_fifo_mem_1_6_62q <= wire_fluid_board_soc_mm_interconnect_0_i2c_master_is1_avalon_slave_0_agent_rdata_fifo_altera_avalon_sc_fifo_i2c_master_is1_avalon_slave_0_agent_rdata_fifo_mem_32m_dataout;
				fluid_board_soc_mm_interconnect_0_i2c_master_is1_avalon_slave_0_agent_rdata_fifo_altera_avalon_sc_fifo_i2c_master_is1_avalon_slave_0_agent_rdata_fifo_mem_1_7_61q <= wire_fluid_board_soc_mm_interconnect_0_i2c_master_is1_avalon_slave_0_agent_rdata_fifo_altera_avalon_sc_fifo_i2c_master_is1_avalon_slave_0_agent_rdata_fifo_mem_31m_dataout;
				fluid_board_soc_mm_interconnect_0_i2c_master_is1_avalon_slave_0_agent_rdata_fifo_altera_avalon_sc_fifo_i2c_master_is1_avalon_slave_0_agent_rdata_fifo_mem_1_8_60q <= wire_fluid_board_soc_mm_interconnect_0_i2c_master_is1_avalon_slave_0_agent_rdata_fifo_altera_avalon_sc_fifo_i2c_master_is1_avalon_slave_0_agent_rdata_fifo_mem_30m_dataout;
				fluid_board_soc_mm_interconnect_0_i2c_master_is1_avalon_slave_0_agent_rdata_fifo_altera_avalon_sc_fifo_i2c_master_is1_avalon_slave_0_agent_rdata_fifo_mem_1_9_59q <= wire_fluid_board_soc_mm_interconnect_0_i2c_master_is1_avalon_slave_0_agent_rdata_fifo_altera_avalon_sc_fifo_i2c_master_is1_avalon_slave_0_agent_rdata_fifo_mem_29m_dataout;
				fluid_board_soc_mm_interconnect_0_i2c_master_is1_avalon_slave_0_agent_rdata_fifo_altera_avalon_sc_fifo_i2c_master_is1_avalon_slave_0_agent_rdata_fifo_mem_used_0_78q <= wire_fluid_board_soc_mm_interconnect_0_i2c_master_is1_avalon_slave_0_agent_rdata_fifo_altera_avalon_sc_fifo_i2c_master_is1_avalon_slave_0_agent_rdata_fifo_mem_used_0_269m_dataout;
				fluid_board_soc_mm_interconnect_0_i2c_master_is1_avalon_slave_0_agent_rdata_fifo_altera_avalon_sc_fifo_i2c_master_is1_avalon_slave_0_agent_rdata_fifo_mem_used_1_131q <= wire_fluid_board_soc_mm_interconnect_0_i2c_master_is1_avalon_slave_0_agent_rdata_fifo_altera_avalon_sc_fifo_i2c_master_is1_avalon_slave_0_agent_rdata_fifo_mem_used_1_270m_dataout;
		END IF;
	END PROCESS;
	wire_nl_w14w(0) <= NOT fluid_board_soc_mm_interconnect_0_i2c_master_is1_avalon_slave_0_agent_rdata_fifo_altera_avalon_sc_fifo_i2c_master_is1_avalon_slave_0_agent_rdata_fifo_mem_used_0_78q;
	wire_nl_w1w(0) <= NOT fluid_board_soc_mm_interconnect_0_i2c_master_is1_avalon_slave_0_agent_rdata_fifo_altera_avalon_sc_fifo_i2c_master_is1_avalon_slave_0_agent_rdata_fifo_mem_used_1_131q;
	PROCESS (clk, reset)
	BEGIN
		IF (reset = '1') THEN
				fluid_board_soc_mm_interconnect_0_i2c_master_is1_avalon_slave_0_agent_rdata_fifo_altera_avalon_sc_fifo_i2c_master_is1_avalon_slave_0_agent_rdata_fifo_mem_0_0_58q <= '0';
				fluid_board_soc_mm_interconnect_0_i2c_master_is1_avalon_slave_0_agent_rdata_fifo_altera_avalon_sc_fifo_i2c_master_is1_avalon_slave_0_agent_rdata_fifo_mem_0_1_57q <= '0';
				fluid_board_soc_mm_interconnect_0_i2c_master_is1_avalon_slave_0_agent_rdata_fifo_altera_avalon_sc_fifo_i2c_master_is1_avalon_slave_0_agent_rdata_fifo_mem_0_2_56q <= '0';
				fluid_board_soc_mm_interconnect_0_i2c_master_is1_avalon_slave_0_agent_rdata_fifo_altera_avalon_sc_fifo_i2c_master_is1_avalon_slave_0_agent_rdata_fifo_mem_0_3_55q <= '0';
				fluid_board_soc_mm_interconnect_0_i2c_master_is1_avalon_slave_0_agent_rdata_fifo_altera_avalon_sc_fifo_i2c_master_is1_avalon_slave_0_agent_rdata_fifo_mem_0_4_54q <= '0';
				fluid_board_soc_mm_interconnect_0_i2c_master_is1_avalon_slave_0_agent_rdata_fifo_altera_avalon_sc_fifo_i2c_master_is1_avalon_slave_0_agent_rdata_fifo_mem_0_5_53q <= '0';
				fluid_board_soc_mm_interconnect_0_i2c_master_is1_avalon_slave_0_agent_rdata_fifo_altera_avalon_sc_fifo_i2c_master_is1_avalon_slave_0_agent_rdata_fifo_mem_0_6_52q <= '0';
				fluid_board_soc_mm_interconnect_0_i2c_master_is1_avalon_slave_0_agent_rdata_fifo_altera_avalon_sc_fifo_i2c_master_is1_avalon_slave_0_agent_rdata_fifo_mem_0_7_51q <= '0';
				fluid_board_soc_mm_interconnect_0_i2c_master_is1_avalon_slave_0_agent_rdata_fifo_altera_avalon_sc_fifo_i2c_master_is1_avalon_slave_0_agent_rdata_fifo_mem_0_8_50q <= '0';
				fluid_board_soc_mm_interconnect_0_i2c_master_is1_avalon_slave_0_agent_rdata_fifo_altera_avalon_sc_fifo_i2c_master_is1_avalon_slave_0_agent_rdata_fifo_mem_0_9_49q <= '0';
		ELSIF (clk = '1' AND clk'event) THEN
			IF (s_wire_fluid_board_soc_mm_interconnect_0_i2c_master_is1_avalon_slave_0_agent_rdata_fifo_altera_avalon_sc_fifo_i2c_master_is1_avalon_slave_0_agent_rdata_fifo_always0_28_dataout = '1') THEN
				fluid_board_soc_mm_interconnect_0_i2c_master_is1_avalon_slave_0_agent_rdata_fifo_altera_avalon_sc_fifo_i2c_master_is1_avalon_slave_0_agent_rdata_fifo_mem_0_0_58q <= wire_fluid_board_soc_mm_interconnect_0_i2c_master_is1_avalon_slave_0_agent_rdata_fifo_altera_avalon_sc_fifo_i2c_master_is1_avalon_slave_0_agent_rdata_fifo_mem_38m_dataout;
				fluid_board_soc_mm_interconnect_0_i2c_master_is1_avalon_slave_0_agent_rdata_fifo_altera_avalon_sc_fifo_i2c_master_is1_avalon_slave_0_agent_rdata_fifo_mem_0_1_57q <= wire_fluid_board_soc_mm_interconnect_0_i2c_master_is1_avalon_slave_0_agent_rdata_fifo_altera_avalon_sc_fifo_i2c_master_is1_avalon_slave_0_agent_rdata_fifo_mem_37m_dataout;
				fluid_board_soc_mm_interconnect_0_i2c_master_is1_avalon_slave_0_agent_rdata_fifo_altera_avalon_sc_fifo_i2c_master_is1_avalon_slave_0_agent_rdata_fifo_mem_0_2_56q <= wire_fluid_board_soc_mm_interconnect_0_i2c_master_is1_avalon_slave_0_agent_rdata_fifo_altera_avalon_sc_fifo_i2c_master_is1_avalon_slave_0_agent_rdata_fifo_mem_36m_dataout;
				fluid_board_soc_mm_interconnect_0_i2c_master_is1_avalon_slave_0_agent_rdata_fifo_altera_avalon_sc_fifo_i2c_master_is1_avalon_slave_0_agent_rdata_fifo_mem_0_3_55q <= wire_fluid_board_soc_mm_interconnect_0_i2c_master_is1_avalon_slave_0_agent_rdata_fifo_altera_avalon_sc_fifo_i2c_master_is1_avalon_slave_0_agent_rdata_fifo_mem_35m_dataout;
				fluid_board_soc_mm_interconnect_0_i2c_master_is1_avalon_slave_0_agent_rdata_fifo_altera_avalon_sc_fifo_i2c_master_is1_avalon_slave_0_agent_rdata_fifo_mem_0_4_54q <= wire_fluid_board_soc_mm_interconnect_0_i2c_master_is1_avalon_slave_0_agent_rdata_fifo_altera_avalon_sc_fifo_i2c_master_is1_avalon_slave_0_agent_rdata_fifo_mem_34m_dataout;
				fluid_board_soc_mm_interconnect_0_i2c_master_is1_avalon_slave_0_agent_rdata_fifo_altera_avalon_sc_fifo_i2c_master_is1_avalon_slave_0_agent_rdata_fifo_mem_0_5_53q <= wire_fluid_board_soc_mm_interconnect_0_i2c_master_is1_avalon_slave_0_agent_rdata_fifo_altera_avalon_sc_fifo_i2c_master_is1_avalon_slave_0_agent_rdata_fifo_mem_33m_dataout;
				fluid_board_soc_mm_interconnect_0_i2c_master_is1_avalon_slave_0_agent_rdata_fifo_altera_avalon_sc_fifo_i2c_master_is1_avalon_slave_0_agent_rdata_fifo_mem_0_6_52q <= wire_fluid_board_soc_mm_interconnect_0_i2c_master_is1_avalon_slave_0_agent_rdata_fifo_altera_avalon_sc_fifo_i2c_master_is1_avalon_slave_0_agent_rdata_fifo_mem_32m_dataout;
				fluid_board_soc_mm_interconnect_0_i2c_master_is1_avalon_slave_0_agent_rdata_fifo_altera_avalon_sc_fifo_i2c_master_is1_avalon_slave_0_agent_rdata_fifo_mem_0_7_51q <= wire_fluid_board_soc_mm_interconnect_0_i2c_master_is1_avalon_slave_0_agent_rdata_fifo_altera_avalon_sc_fifo_i2c_master_is1_avalon_slave_0_agent_rdata_fifo_mem_31m_dataout;
				fluid_board_soc_mm_interconnect_0_i2c_master_is1_avalon_slave_0_agent_rdata_fifo_altera_avalon_sc_fifo_i2c_master_is1_avalon_slave_0_agent_rdata_fifo_mem_0_8_50q <= wire_fluid_board_soc_mm_interconnect_0_i2c_master_is1_avalon_slave_0_agent_rdata_fifo_altera_avalon_sc_fifo_i2c_master_is1_avalon_slave_0_agent_rdata_fifo_mem_30m_dataout;
				fluid_board_soc_mm_interconnect_0_i2c_master_is1_avalon_slave_0_agent_rdata_fifo_altera_avalon_sc_fifo_i2c_master_is1_avalon_slave_0_agent_rdata_fifo_mem_0_9_49q <= wire_fluid_board_soc_mm_interconnect_0_i2c_master_is1_avalon_slave_0_agent_rdata_fifo_altera_avalon_sc_fifo_i2c_master_is1_avalon_slave_0_agent_rdata_fifo_mem_29m_dataout;
			END IF;
		END IF;
	END PROCESS;
	wire_fluid_board_soc_mm_interconnect_0_i2c_master_is1_avalon_slave_0_agent_rdata_fifo_altera_avalon_sc_fifo_i2c_master_is1_avalon_slave_0_agent_rdata_fifo_mem_29m_dataout <= in_data(9) WHEN wire_nl_w1w(0) = '1'  ELSE fluid_board_soc_mm_interconnect_0_i2c_master_is1_avalon_slave_0_agent_rdata_fifo_altera_avalon_sc_fifo_i2c_master_is1_avalon_slave_0_agent_rdata_fifo_mem_1_9_59q;
	wire_fluid_board_soc_mm_interconnect_0_i2c_master_is1_avalon_slave_0_agent_rdata_fifo_altera_avalon_sc_fifo_i2c_master_is1_avalon_slave_0_agent_rdata_fifo_mem_30m_dataout <= in_data(8) WHEN wire_nl_w1w(0) = '1'  ELSE fluid_board_soc_mm_interconnect_0_i2c_master_is1_avalon_slave_0_agent_rdata_fifo_altera_avalon_sc_fifo_i2c_master_is1_avalon_slave_0_agent_rdata_fifo_mem_1_8_60q;
	wire_fluid_board_soc_mm_interconnect_0_i2c_master_is1_avalon_slave_0_agent_rdata_fifo_altera_avalon_sc_fifo_i2c_master_is1_avalon_slave_0_agent_rdata_fifo_mem_31m_dataout <= in_data(7) WHEN wire_nl_w1w(0) = '1'  ELSE fluid_board_soc_mm_interconnect_0_i2c_master_is1_avalon_slave_0_agent_rdata_fifo_altera_avalon_sc_fifo_i2c_master_is1_avalon_slave_0_agent_rdata_fifo_mem_1_7_61q;
	wire_fluid_board_soc_mm_interconnect_0_i2c_master_is1_avalon_slave_0_agent_rdata_fifo_altera_avalon_sc_fifo_i2c_master_is1_avalon_slave_0_agent_rdata_fifo_mem_32m_dataout <= in_data(6) WHEN wire_nl_w1w(0) = '1'  ELSE fluid_board_soc_mm_interconnect_0_i2c_master_is1_avalon_slave_0_agent_rdata_fifo_altera_avalon_sc_fifo_i2c_master_is1_avalon_slave_0_agent_rdata_fifo_mem_1_6_62q;
	wire_fluid_board_soc_mm_interconnect_0_i2c_master_is1_avalon_slave_0_agent_rdata_fifo_altera_avalon_sc_fifo_i2c_master_is1_avalon_slave_0_agent_rdata_fifo_mem_33m_dataout <= in_data(5) WHEN wire_nl_w1w(0) = '1'  ELSE fluid_board_soc_mm_interconnect_0_i2c_master_is1_avalon_slave_0_agent_rdata_fifo_altera_avalon_sc_fifo_i2c_master_is1_avalon_slave_0_agent_rdata_fifo_mem_1_5_63q;
	wire_fluid_board_soc_mm_interconnect_0_i2c_master_is1_avalon_slave_0_agent_rdata_fifo_altera_avalon_sc_fifo_i2c_master_is1_avalon_slave_0_agent_rdata_fifo_mem_34m_dataout <= in_data(4) WHEN wire_nl_w1w(0) = '1'  ELSE fluid_board_soc_mm_interconnect_0_i2c_master_is1_avalon_slave_0_agent_rdata_fifo_altera_avalon_sc_fifo_i2c_master_is1_avalon_slave_0_agent_rdata_fifo_mem_1_4_64q;
	wire_fluid_board_soc_mm_interconnect_0_i2c_master_is1_avalon_slave_0_agent_rdata_fifo_altera_avalon_sc_fifo_i2c_master_is1_avalon_slave_0_agent_rdata_fifo_mem_35m_dataout <= in_data(3) WHEN wire_nl_w1w(0) = '1'  ELSE fluid_board_soc_mm_interconnect_0_i2c_master_is1_avalon_slave_0_agent_rdata_fifo_altera_avalon_sc_fifo_i2c_master_is1_avalon_slave_0_agent_rdata_fifo_mem_1_3_65q;
	wire_fluid_board_soc_mm_interconnect_0_i2c_master_is1_avalon_slave_0_agent_rdata_fifo_altera_avalon_sc_fifo_i2c_master_is1_avalon_slave_0_agent_rdata_fifo_mem_36m_dataout <= in_data(2) WHEN wire_nl_w1w(0) = '1'  ELSE fluid_board_soc_mm_interconnect_0_i2c_master_is1_avalon_slave_0_agent_rdata_fifo_altera_avalon_sc_fifo_i2c_master_is1_avalon_slave_0_agent_rdata_fifo_mem_1_2_66q;
	wire_fluid_board_soc_mm_interconnect_0_i2c_master_is1_avalon_slave_0_agent_rdata_fifo_altera_avalon_sc_fifo_i2c_master_is1_avalon_slave_0_agent_rdata_fifo_mem_37m_dataout <= in_data(1) WHEN wire_nl_w1w(0) = '1'  ELSE fluid_board_soc_mm_interconnect_0_i2c_master_is1_avalon_slave_0_agent_rdata_fifo_altera_avalon_sc_fifo_i2c_master_is1_avalon_slave_0_agent_rdata_fifo_mem_1_1_67q;
	wire_fluid_board_soc_mm_interconnect_0_i2c_master_is1_avalon_slave_0_agent_rdata_fifo_altera_avalon_sc_fifo_i2c_master_is1_avalon_slave_0_agent_rdata_fifo_mem_38m_dataout <= in_data(0) WHEN wire_nl_w1w(0) = '1'  ELSE fluid_board_soc_mm_interconnect_0_i2c_master_is1_avalon_slave_0_agent_rdata_fifo_altera_avalon_sc_fifo_i2c_master_is1_avalon_slave_0_agent_rdata_fifo_mem_1_0_75q;
	wire_fluid_board_soc_mm_interconnect_0_i2c_master_is1_avalon_slave_0_agent_rdata_fifo_altera_avalon_sc_fifo_i2c_master_is1_avalon_slave_0_agent_rdata_fifo_mem_used_0_269m_dataout <= wire_fluid_board_soc_mm_interconnect_0_i2c_master_is1_avalon_slave_0_agent_rdata_fifo_altera_avalon_sc_fifo_i2c_master_is1_avalon_slave_0_agent_rdata_fifo_mem_used_73m_dataout WHEN s_wire_fluid_board_soc_mm_interconnect_0_i2c_master_is1_avalon_slave_0_agent_rdata_fifo_altera_avalon_sc_fifo_i2c_master_is1_avalon_slave_0_agent_rdata_fifo_always2_71_dataout = '1'  ELSE fluid_board_soc_mm_interconnect_0_i2c_master_is1_avalon_slave_0_agent_rdata_fifo_altera_avalon_sc_fifo_i2c_master_is1_avalon_slave_0_agent_rdata_fifo_mem_used_0_78q;
	wire_fluid_board_soc_mm_interconnect_0_i2c_master_is1_avalon_slave_0_agent_rdata_fifo_altera_avalon_sc_fifo_i2c_master_is1_avalon_slave_0_agent_rdata_fifo_mem_used_1_270m_dataout <= wire_fluid_board_soc_mm_interconnect_0_i2c_master_is1_avalon_slave_0_agent_rdata_fifo_altera_avalon_sc_fifo_i2c_master_is1_avalon_slave_0_agent_rdata_fifo_mem_used_76m_dataout WHEN s_wire_fluid_board_soc_mm_interconnect_0_i2c_master_is1_avalon_slave_0_agent_rdata_fifo_altera_avalon_sc_fifo_i2c_master_is1_avalon_slave_0_agent_rdata_fifo_always2_71_dataout = '1'  ELSE fluid_board_soc_mm_interconnect_0_i2c_master_is1_avalon_slave_0_agent_rdata_fifo_altera_avalon_sc_fifo_i2c_master_is1_avalon_slave_0_agent_rdata_fifo_mem_used_1_131q;
	wire_fluid_board_soc_mm_interconnect_0_i2c_master_is1_avalon_slave_0_agent_rdata_fifo_altera_avalon_sc_fifo_i2c_master_is1_avalon_slave_0_agent_rdata_fifo_mem_used_72m_dataout <= fluid_board_soc_mm_interconnect_0_i2c_master_is1_avalon_slave_0_agent_rdata_fifo_altera_avalon_sc_fifo_i2c_master_is1_avalon_slave_0_agent_rdata_fifo_mem_used_1_131q WHEN s_wire_fluid_board_soc_mm_interconnect_0_i2c_master_is1_avalon_slave_0_agent_rdata_fifo_altera_avalon_sc_fifo_i2c_master_is1_avalon_slave_0_agent_rdata_fifo_read_68_dataout = '1'  ELSE fluid_board_soc_mm_interconnect_0_i2c_master_is1_avalon_slave_0_agent_rdata_fifo_altera_avalon_sc_fifo_i2c_master_is1_avalon_slave_0_agent_rdata_fifo_mem_used_0_78q;
	wire_fluid_board_soc_mm_interconnect_0_i2c_master_is1_avalon_slave_0_agent_rdata_fifo_altera_avalon_sc_fifo_i2c_master_is1_avalon_slave_0_agent_rdata_fifo_mem_used_73m_dataout <= wire_fluid_board_soc_mm_interconnect_0_i2c_master_is1_avalon_slave_0_agent_rdata_fifo_altera_avalon_sc_fifo_i2c_master_is1_avalon_slave_0_agent_rdata_fifo_mem_used_72m_dataout OR s_wire_fluid_board_soc_mm_interconnect_0_i2c_master_is1_avalon_slave_0_agent_rdata_fifo_altera_avalon_sc_fifo_i2c_master_is1_avalon_slave_0_agent_rdata_fifo_write_70_dataout;
	wire_fluid_board_soc_mm_interconnect_0_i2c_master_is1_avalon_slave_0_agent_rdata_fifo_altera_avalon_sc_fifo_i2c_master_is1_avalon_slave_0_agent_rdata_fifo_mem_used_76m_dataout <= fluid_board_soc_mm_interconnect_0_i2c_master_is1_avalon_slave_0_agent_rdata_fifo_altera_avalon_sc_fifo_i2c_master_is1_avalon_slave_0_agent_rdata_fifo_mem_used_0_78q AND s_wire_fluid_board_soc_mm_interconnect_0_i2c_master_is1_avalon_slave_0_agent_rdata_fifo_altera_avalon_sc_fifo_i2c_master_is1_avalon_slave_0_agent_rdata_fifo_write_70_dataout;
	wire_fluid_board_soc_mm_interconnect_0_i2c_master_is1_avalon_slave_0_agent_rdata_fifo_altera_avalon_sc_fifo_i2c_master_is1_avalon_slave_0_agent_rdata_fifo_out_data_0_93m_dataout <= in_data(0) WHEN s_wire_fluid_board_soc_mm_interconnect_0_i2c_master_is1_avalon_slave_0_agent_rdata_fifo_altera_avalon_sc_fifo_i2c_master_is1_avalon_slave_0_agent_rdata_fifo_always4_83_dataout = '1'  ELSE fluid_board_soc_mm_interconnect_0_i2c_master_is1_avalon_slave_0_agent_rdata_fifo_altera_avalon_sc_fifo_i2c_master_is1_avalon_slave_0_agent_rdata_fifo_mem_0_0_58q;
	wire_fluid_board_soc_mm_interconnect_0_i2c_master_is1_avalon_slave_0_agent_rdata_fifo_altera_avalon_sc_fifo_i2c_master_is1_avalon_slave_0_agent_rdata_fifo_out_data_1_92m_dataout <= in_data(1) WHEN s_wire_fluid_board_soc_mm_interconnect_0_i2c_master_is1_avalon_slave_0_agent_rdata_fifo_altera_avalon_sc_fifo_i2c_master_is1_avalon_slave_0_agent_rdata_fifo_always4_83_dataout = '1'  ELSE fluid_board_soc_mm_interconnect_0_i2c_master_is1_avalon_slave_0_agent_rdata_fifo_altera_avalon_sc_fifo_i2c_master_is1_avalon_slave_0_agent_rdata_fifo_mem_0_1_57q;
	wire_fluid_board_soc_mm_interconnect_0_i2c_master_is1_avalon_slave_0_agent_rdata_fifo_altera_avalon_sc_fifo_i2c_master_is1_avalon_slave_0_agent_rdata_fifo_out_data_2_91m_dataout <= in_data(2) WHEN s_wire_fluid_board_soc_mm_interconnect_0_i2c_master_is1_avalon_slave_0_agent_rdata_fifo_altera_avalon_sc_fifo_i2c_master_is1_avalon_slave_0_agent_rdata_fifo_always4_83_dataout = '1'  ELSE fluid_board_soc_mm_interconnect_0_i2c_master_is1_avalon_slave_0_agent_rdata_fifo_altera_avalon_sc_fifo_i2c_master_is1_avalon_slave_0_agent_rdata_fifo_mem_0_2_56q;
	wire_fluid_board_soc_mm_interconnect_0_i2c_master_is1_avalon_slave_0_agent_rdata_fifo_altera_avalon_sc_fifo_i2c_master_is1_avalon_slave_0_agent_rdata_fifo_out_data_3_90m_dataout <= in_data(3) WHEN s_wire_fluid_board_soc_mm_interconnect_0_i2c_master_is1_avalon_slave_0_agent_rdata_fifo_altera_avalon_sc_fifo_i2c_master_is1_avalon_slave_0_agent_rdata_fifo_always4_83_dataout = '1'  ELSE fluid_board_soc_mm_interconnect_0_i2c_master_is1_avalon_slave_0_agent_rdata_fifo_altera_avalon_sc_fifo_i2c_master_is1_avalon_slave_0_agent_rdata_fifo_mem_0_3_55q;
	wire_fluid_board_soc_mm_interconnect_0_i2c_master_is1_avalon_slave_0_agent_rdata_fifo_altera_avalon_sc_fifo_i2c_master_is1_avalon_slave_0_agent_rdata_fifo_out_data_4_89m_dataout <= in_data(4) WHEN s_wire_fluid_board_soc_mm_interconnect_0_i2c_master_is1_avalon_slave_0_agent_rdata_fifo_altera_avalon_sc_fifo_i2c_master_is1_avalon_slave_0_agent_rdata_fifo_always4_83_dataout = '1'  ELSE fluid_board_soc_mm_interconnect_0_i2c_master_is1_avalon_slave_0_agent_rdata_fifo_altera_avalon_sc_fifo_i2c_master_is1_avalon_slave_0_agent_rdata_fifo_mem_0_4_54q;
	wire_fluid_board_soc_mm_interconnect_0_i2c_master_is1_avalon_slave_0_agent_rdata_fifo_altera_avalon_sc_fifo_i2c_master_is1_avalon_slave_0_agent_rdata_fifo_out_data_5_88m_dataout <= in_data(5) WHEN s_wire_fluid_board_soc_mm_interconnect_0_i2c_master_is1_avalon_slave_0_agent_rdata_fifo_altera_avalon_sc_fifo_i2c_master_is1_avalon_slave_0_agent_rdata_fifo_always4_83_dataout = '1'  ELSE fluid_board_soc_mm_interconnect_0_i2c_master_is1_avalon_slave_0_agent_rdata_fifo_altera_avalon_sc_fifo_i2c_master_is1_avalon_slave_0_agent_rdata_fifo_mem_0_5_53q;
	wire_fluid_board_soc_mm_interconnect_0_i2c_master_is1_avalon_slave_0_agent_rdata_fifo_altera_avalon_sc_fifo_i2c_master_is1_avalon_slave_0_agent_rdata_fifo_out_data_6_87m_dataout <= in_data(6) WHEN s_wire_fluid_board_soc_mm_interconnect_0_i2c_master_is1_avalon_slave_0_agent_rdata_fifo_altera_avalon_sc_fifo_i2c_master_is1_avalon_slave_0_agent_rdata_fifo_always4_83_dataout = '1'  ELSE fluid_board_soc_mm_interconnect_0_i2c_master_is1_avalon_slave_0_agent_rdata_fifo_altera_avalon_sc_fifo_i2c_master_is1_avalon_slave_0_agent_rdata_fifo_mem_0_6_52q;
	wire_fluid_board_soc_mm_interconnect_0_i2c_master_is1_avalon_slave_0_agent_rdata_fifo_altera_avalon_sc_fifo_i2c_master_is1_avalon_slave_0_agent_rdata_fifo_out_data_7_86m_dataout <= in_data(7) WHEN s_wire_fluid_board_soc_mm_interconnect_0_i2c_master_is1_avalon_slave_0_agent_rdata_fifo_altera_avalon_sc_fifo_i2c_master_is1_avalon_slave_0_agent_rdata_fifo_always4_83_dataout = '1'  ELSE fluid_board_soc_mm_interconnect_0_i2c_master_is1_avalon_slave_0_agent_rdata_fifo_altera_avalon_sc_fifo_i2c_master_is1_avalon_slave_0_agent_rdata_fifo_mem_0_7_51q;
	wire_fluid_board_soc_mm_interconnect_0_i2c_master_is1_avalon_slave_0_agent_rdata_fifo_altera_avalon_sc_fifo_i2c_master_is1_avalon_slave_0_agent_rdata_fifo_out_data_8_85m_dataout <= in_data(8) WHEN s_wire_fluid_board_soc_mm_interconnect_0_i2c_master_is1_avalon_slave_0_agent_rdata_fifo_altera_avalon_sc_fifo_i2c_master_is1_avalon_slave_0_agent_rdata_fifo_always4_83_dataout = '1'  ELSE fluid_board_soc_mm_interconnect_0_i2c_master_is1_avalon_slave_0_agent_rdata_fifo_altera_avalon_sc_fifo_i2c_master_is1_avalon_slave_0_agent_rdata_fifo_mem_0_8_50q;
	wire_fluid_board_soc_mm_interconnect_0_i2c_master_is1_avalon_slave_0_agent_rdata_fifo_altera_avalon_sc_fifo_i2c_master_is1_avalon_slave_0_agent_rdata_fifo_out_data_9_84m_dataout <= in_data(9) WHEN s_wire_fluid_board_soc_mm_interconnect_0_i2c_master_is1_avalon_slave_0_agent_rdata_fifo_altera_avalon_sc_fifo_i2c_master_is1_avalon_slave_0_agent_rdata_fifo_always4_83_dataout = '1'  ELSE fluid_board_soc_mm_interconnect_0_i2c_master_is1_avalon_slave_0_agent_rdata_fifo_altera_avalon_sc_fifo_i2c_master_is1_avalon_slave_0_agent_rdata_fifo_mem_0_9_49q;

 END RTL; --fluid_board_soc_mm_interconnect_0_i2c_master_is1_avalon_slave_0_agent_rdata_fifo
--synopsys translate_on
--VALID FILE
