# TCL File Generated by Component Editor 15.1
# Tue Aug 02 11:14:55 CEST 2016
# DO NOT MODIFY


# 
# axi_lw_slave_register "axi_lw_slave_register" v15.1
# sebastian@radex-net.com 2016.08.02.11:14:55
# 
# 

# 
# request TCL package from ACDS 15.1
# 
package require -exact qsys 15.1


# 
# module axi_lw_slave_register
# 
set_module_property DESCRIPTION ""
set_module_property NAME axi_lw_slave_register
set_module_property VERSION 15.1
set_module_property INTERNAL false
set_module_property OPAQUE_ADDRESS_MAP true
set_module_property GROUP Other
set_module_property AUTHOR sebastian@radex-net.com
set_module_property DISPLAY_NAME axi_lw_slave_register
set_module_property INSTANTIATE_IN_SYSTEM_MODULE true
set_module_property EDITABLE true
set_module_property REPORT_TO_TALKBACK false
set_module_property ALLOW_GREYBOX_GENERATION false
set_module_property REPORT_HIERARCHY false


# 
# file sets
# 
add_fileset QUARTUS_SYNTH QUARTUS_SYNTH "" ""
set_fileset_property QUARTUS_SYNTH TOP_LEVEL axi_lw_slave_register
set_fileset_property QUARTUS_SYNTH ENABLE_RELATIVE_INCLUDE_PATHS false
set_fileset_property QUARTUS_SYNTH ENABLE_FILE_OVERWRITE_MODE false
add_fileset_file axi_lw_slave_register_rtl.vhd VHDL PATH ip/axi_lw_slave_register/axi_lw_slave_register_rtl.vhd


# 
# parameters
# 
add_parameter g_master_id_width INTEGER 12
set_parameter_property g_master_id_width DEFAULT_VALUE 12
set_parameter_property g_master_id_width DISPLAY_NAME g_master_id_width
set_parameter_property g_master_id_width TYPE INTEGER
set_parameter_property g_master_id_width UNITS None
set_parameter_property g_master_id_width ALLOWED_RANGES -2147483648:2147483647
set_parameter_property g_master_id_width HDL_PARAMETER true
add_parameter g_master_data_width INTEGER 32
set_parameter_property g_master_data_width DEFAULT_VALUE 32
set_parameter_property g_master_data_width DISPLAY_NAME g_master_data_width
set_parameter_property g_master_data_width TYPE INTEGER
set_parameter_property g_master_data_width UNITS None
set_parameter_property g_master_data_width ALLOWED_RANGES -2147483648:2147483647
set_parameter_property g_master_data_width HDL_PARAMETER true
add_parameter g_master_addr_width INTEGER 16
set_parameter_property g_master_addr_width DEFAULT_VALUE 16
set_parameter_property g_master_addr_width DISPLAY_NAME g_master_addr_width
set_parameter_property g_master_addr_width TYPE INTEGER
set_parameter_property g_master_addr_width UNITS None
set_parameter_property g_master_addr_width ALLOWED_RANGES -2147483648:2147483647
set_parameter_property g_master_addr_width HDL_PARAMETER true


# 
# display items
# 


# 
# connection point reset
# 
add_interface reset reset end
set_interface_property reset associatedClock clock
set_interface_property reset synchronousEdges DEASSERT
set_interface_property reset ENABLED true
set_interface_property reset EXPORT_OF ""
set_interface_property reset PORT_NAME_MAP ""
set_interface_property reset CMSIS_SVD_VARIABLES ""
set_interface_property reset SVD_ADDRESS_GROUP ""

add_interface_port reset rsi_reset_reset_n reset_n Input 1


# 
# connection point clock
# 
add_interface clock clock end
set_interface_property clock clockRate 50000000
set_interface_property clock ENABLED true
set_interface_property clock EXPORT_OF ""
set_interface_property clock PORT_NAME_MAP ""
set_interface_property clock CMSIS_SVD_VARIABLES ""
set_interface_property clock SVD_ADDRESS_GROUP ""

add_interface_port clock csi_clock_clk clk Input 1


# 
# connection point conduit_end_0
# 
add_interface conduit_end_0 conduit end
set_interface_property conduit_end_0 associatedClock clock
set_interface_property conduit_end_0 associatedReset reset
set_interface_property conduit_end_0 ENABLED true
set_interface_property conduit_end_0 EXPORT_OF ""
set_interface_property conduit_end_0 PORT_NAME_MAP ""
set_interface_property conduit_end_0 CMSIS_SVD_VARIABLES ""
set_interface_property conduit_end_0 SVD_ADDRESS_GROUP ""

add_interface_port conduit_end_0 coe_wr_strb wr_strb Output 4
add_interface_port conduit_end_0 coe_wr_valid wr_valid Output 1
add_interface_port conduit_end_0 coe_rd_addr rd_addr Output g_master_addr_width
add_interface_port conduit_end_0 coe_rd_data rd_data Input g_master_data_width
add_interface_port conduit_end_0 coe_rd_valid rd_valid Output 1
add_interface_port conduit_end_0 coe_rd_ready rd_ready Input 1
add_interface_port conduit_end_0 coe_wr_data wr_data Output g_master_data_width
add_interface_port conduit_end_0 coe_wr_addr wr_addr Output g_master_addr_width


# 
# connection point altera_axi4lite_slave
# 
add_interface altera_axi4lite_slave axi4lite end
set_interface_property altera_axi4lite_slave associatedClock clock
set_interface_property altera_axi4lite_slave associatedReset reset
set_interface_property altera_axi4lite_slave readAcceptanceCapability 1
set_interface_property altera_axi4lite_slave writeAcceptanceCapability 1
set_interface_property altera_axi4lite_slave combinedAcceptanceCapability 1
set_interface_property altera_axi4lite_slave readDataReorderingDepth 1
set_interface_property altera_axi4lite_slave bridgesToMaster ""
set_interface_property altera_axi4lite_slave ENABLED true
set_interface_property altera_axi4lite_slave EXPORT_OF ""
set_interface_property altera_axi4lite_slave PORT_NAME_MAP ""
set_interface_property altera_axi4lite_slave CMSIS_SVD_VARIABLES ""
set_interface_property altera_axi4lite_slave SVD_ADDRESS_GROUP ""

add_interface_port altera_axi4lite_slave axs_awaddr awaddr Input g_master_addr_width
add_interface_port altera_axi4lite_slave axs_awprot awprot Input 3
add_interface_port altera_axi4lite_slave axs_awvalid awvalid Input 1
add_interface_port altera_axi4lite_slave axs_awready awready Output 1
add_interface_port altera_axi4lite_slave axs_wdata wdata Input g_master_data_width
add_interface_port altera_axi4lite_slave axs_wstrb wstrb Input 4
add_interface_port altera_axi4lite_slave axs_wvalid wvalid Input 1
add_interface_port altera_axi4lite_slave axs_wready wready Output 1
add_interface_port altera_axi4lite_slave axs_bresp bresp Output 2
add_interface_port altera_axi4lite_slave axs_bvalid bvalid Output 1
add_interface_port altera_axi4lite_slave axs_bready bready Input 1
add_interface_port altera_axi4lite_slave axs_araddr araddr Input g_master_addr_width
add_interface_port altera_axi4lite_slave axs_arprot arprot Input 3
add_interface_port altera_axi4lite_slave axs_arvalid arvalid Input 1
add_interface_port altera_axi4lite_slave axs_arready arready Output 1
add_interface_port altera_axi4lite_slave axs_rdata rdata Output g_master_data_width
add_interface_port altera_axi4lite_slave axs_rresp rresp Output 2
add_interface_port altera_axi4lite_slave axs_rvalid rvalid Output 1
add_interface_port altera_axi4lite_slave axs_rready rready Input 1

